// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $test_layout from "./routes/test/_layout.tsx";
import * as $test_page1 from "./routes/test/page1.tsx";
import * as $test_page2 from "./routes/test/page2.tsx";
import * as $test_subtest_layout from "./routes/test/subtest/_layout.tsx";
import * as $test_subtest_page3 from "./routes/test/subtest/page3.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/test/_layout.tsx": $test_layout,
    "./routes/test/page1.tsx": $test_page1,
    "./routes/test/page2.tsx": $test_page2,
    "./routes/test/subtest/_layout.tsx": $test_subtest_layout,
    "./routes/test/subtest/page3.tsx": $test_subtest_page3,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
